rhythm_library:
 rhythm_1:
  bpm: 60
  play_duration(sec): 119
  playbutton_click_count: 3
  sequence:
   kick: [2,4,6,10,12,16]
   snare: [3,6,8,14]
   hc: [2,4,5,12,16]
   ho: [4,7,10,15]
 rhythm_2:
  bpm: 110
  play_duration(sec): 100
  playbutton_click_count: 3
  sequence:
   kick: [3,7,8,10,12,15,16]
   snare: [6,9,11,12,14]
   hc: [2,4,7,9,10,16]
   ho: [3,5,8,11,13,14]
 rhythm_3:
  bpm: 50
  play_duration(sec): 30
  playbutton_click_count: 1
  sequence:
   kick: [5,6,9,10,13,16]
   snare: [3,7,8,9,11,12,15]
   hc: [4,6,10,13]
   ho: [2,4,8,10,14,16]
 rhythm_4:
  bpm: 90
  play_duration(sec): 69
  playbutton_click_count: 2
  sequence:
   kick: [4,6,12,14,16]
   snare: [2,7,9,10,13,15]
   hc: [2,4,5,11,13,15]
   ho: [2,7,9,11,14,16]